version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: db_aftas
    ports:
      - "3306:3306"
  aftasbackend:
    image: aftasbackend:v1
    container_name: aftasbackend
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_aftas?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql
#  aftasfrontend:
#    image: aftasfront:v1
#    container_name: aftasfront
#    ports:
#      - "4200:80"
#    depends_on:
#      - aftasbackend